### ISSUE TITLE
Preview image error

### ISSUE THREAD

**Issue by vralle** [BracketSpace/Easy-Watermark#6]
Hi!
I am creating the first text watermark. But no preview image. EW 1.0.5
Errors:
```
PHP Notice:  Undefined index: position_x in ...\plugins\easy-watermark\src\classes\Core\Installer.php on line 191
PHP Notice:  Undefined index: position_y in ...\plugins\easy-watermark\src\classes\Core\Installer.php on line 191
```

```
Request URL: https://site.url/easy-watermark-preview/image-729-full.png?t=digits
Request Method: GET
Status Code: 404 Not Found
Referer: https://site.url/wp-admin/post.php?post=729&action=edit
```
Request URL correct?

**Comment by jakubmikita** [comment]
Hi @vralle have you tried to go to Settings -> Permalinks and click Save?

This will most likely help for the preview issue.

**Comment by vralle** [comment]
Hi @Kubitomakita!
By this time I refused to use the plugin. Maybe I can return to using Easy-Watermark again if the plug-in becomes stable enough, as it was before version 0.7.0.
