### ISSUE TITLE
Always running Installer::update( $last_version, $settings->get_settings() );

### ISSUE THREAD

**Issue by mytryk** [BracketSpace/Easy-Watermark#7]
So next code running on each request:
if ( version_compare( $from, '1.0.0', '>=' ) ) {
  self::update_attachment_meta();
  return;
}
...
Because my version 1.0.8

Have a nice day!

**Comment by jakubmikita** [comment]
Thanks for the notice. This was already fixed and today we're releasing 1.0.10 as well
