### ISSUE TITLE
Preview broken on composer wordpress setup

### ISSUE THREAD

**Issue by joejordanbrown** [BracketSpace/Easy-Watermark#8]
@Kubitomakita @szaleq 

The preview is broken because it uses `site_url` instead of `home_url`.

A standard install of roots/trellis would use a subdirectory for the WordPress core files, to be exact `/wp/` is the default when the root `domain.tld` would load the site and not `domain.tld/wp/`. This is the same if you're installing WordPress via any composer type structured code base.

These are the WordPress options that cause this plugin issues with the preview

**WordPress Address (URL):** `https://domain.tld/wp`
**Site Address (URL):** `https://domain.tld`

The preview would try to load `https://domain.tld/wp/easy-watermark-preview/...` when it should be `https://domain.tld/easy-watermark-preview/...`

**The fix would be on this line replacing `site_url` with `home_url`** https://github.com/BracketSpace/Easy-Watermark/blob/15a33b5aebc5635113cea65aa5f87797569adc04/src/classes/Features/WatermarkPreview.php#L58

**Comment by szaleq** [comment]
@joejordanbrown Thanks for pointing this out. This fix will be included in the next release.
